services:
  - type: web
    name: koshur-canvas
    runtime: node
    buildCommand: npx prisma generate && npx prisma db push --skip-generate && npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./db/custom.db
      - key: PORT
        generateValue: true
    healthCheckPath: /